name: Ping Domains
on:
  push:
    branches:
      - main

jobs:
  ping_domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Domains from File
        id: read_domains
        run: |
          echo "::set-output name=domains::$(cat domains.txt)"

      - name: Ping Domains
        run: |
          for domain in ${{ steps.read_domains.outputs.domains }}; do
            ping -c 5 $domain
          done
